export const raceInfoSample = {
        raceInfo: {
            apiRaceId: "342729",
            raceName: "Tour de France",
            stage: "Stage 1",
            date: "2018-07-07T00:00:00.000Z",
            distance: "201",
            departureCity: "Noirmoutier-En-L'Ile",
            arrivalCity: "Fontenay-le-Comte",
            classification: "flat",
        },
        riders: [
            {
                _id: "5bee8eb781239eae881f26a8",
                displayName: "Axel Domont",
                normName: "axel-domont",
                nationality: "France",
                team: "ag2r-la-mondiale",
                pageUrl: "https://www.procyclingstats.com/rider/axel-domont",
                age: "28",
                height: "1.79",
                weight: "65",
                grandTours: 7,
                classicRaces: 3,
                proWins: 1,
                sportRadarId: "sr:rider:114623",
            },
            {
                _id: "5bee8eb781239eae881f2807",
                displayName: "Ilnur Zakarin",
                normName: "ilnur-zakarin",
                nationality: "Russia",
                team: "team-katusha-alpecin",
                pageUrl: "https://www.procyclingstats.com/rider/ilnur-zakarin",
                age: "29",
                height: "1.87",
                weight: "67",
                grandTours: 7,
                classicRaces: 4,
                proWins: 7,
                sportRadarId: "sr:rider:123378",
            },
            {
                _id: "5bee8eb781239eae881f2809",
                displayName: "Pavel Kochetkov",
                normName: "pavel-kochetkov",
                nationality: "Russia",
                team: "team-katusha-alpecin",
                pageUrl: "https://www.procyclingstats.com/rider/pavel-kochetkov",
                age: "32",
                height: "1.84",
                weight: "72",
                grandTours: 7,
                classicRaces: 4,
                proWins: 1,
                sportRadarId: "sr:rider:123842",
            },
            {
                _id: "5bee8eb781239eae881f26c8",
                displayName: "Magnus Cort",
                normName: "magnus-cort-nielsen",
                nationality: "Denmark",
                team: "astana-pro-team",
                pageUrl: "https://www.procyclingstats.com/rider/magnus-cort-nielsen",
                age: "25",
                height: null,
                weight: "68",
                grandTours: 3,
                classicRaces: 10,
                proWins: 13,
                sportRadarId: "sr:rider:123874",
            },
            {
                _id: "5bee8eb781239eae881f26d7",
                displayName: "Michael Valgren",
                normName: "michael-valgren-andersen",
                nationality: "Denmark",
                team: "astana-pro-team",
                pageUrl: "https://www.procyclingstats.com/rider/michael-valgren-andersen",
                age: "26",
                height: "1.79",
                weight: "71",
                grandTours: 5,
                classicRaces: 8,
                proWins: 6,
                sportRadarId: "sr:rider:123880",
            },
            {
                _id: "5bee8eb781239eae881f26ca",
                displayName: "Jesper Hansen",
                normName: "jesper-hansen-1",
                nationality: "Denmark",
                team: "astana-pro-team",
                pageUrl: "https://www.procyclingstats.com/rider/jesper-hansen-1",
                age: "28",
                height: "1.76",
                weight: "60",
                grandTours: 4,
                classicRaces: 3,
                proWins: 2,
                sportRadarId: "sr:rider:123882",
            },
            {
                _id: "5bee8eb781239eae881f2865",
                displayName: "Søren Kragh Andersen",
                normName: "soren-kragh-andersen",
                nationality: "Denmark",
                team: "team-sunweb",
                pageUrl: "https://www.procyclingstats.com/rider/soren-kragh-andersen",
                age: "24",
                height: "1.78",
                weight: "73",
                grandTours: 2,
                classicRaces: 8,
                proWins: 4,
                sportRadarId: "sr:rider:123886",
            },
            {
                _id: "5bee8eb781239eae881f276f",
                displayName: "Adam Yates",
                normName: "adam-yates",
                nationality: "Great",
                team: "mitchelton-scott",
                pageUrl: "https://www.procyclingstats.com/rider/adam-yates",
                age: "26",
                height: "1.73",
                weight: "58",
                grandTours: 7,
                classicRaces: 6,
                proWins: 7,
                sportRadarId: "sr:rider:123892",
            },
            {
                _id: "5bee8eb781239eae881f286d",
                displayName: "Tsgabu Grmay",
                normName: "tsgabu-gebremaryam-grmay",
                nationality: "Ethiopia",
                team: "trek-segafredo",
                pageUrl: "https://www.procyclingstats.com/rider/tsgabu-gebremaryam-grmay",
                age: "27",
                height: "1.75",
                weight: "63",
                grandTours: 6,
                classicRaces: 3,
                proWins: 10,
                sportRadarId: "sr:rider:125066",
            },
            {
                _id: "5bee8eb781239eae881f27b5",
                displayName: "Julian Alaphilippe",
                normName: "julian-alaphilippe",
                nationality: "France",
                team: "quick-step-floors",
                pageUrl: "https://www.procyclingstats.com/rider/julian-alaphilippe",
                age: "26",
                height: "1.73",
                weight: "62",
                grandTours: 3,
                classicRaces: 8,
                proWins: 18,
                sportRadarId: "sr:rider:135924",
            },
            {
                _id: "5bee8eb781239eae881f27fc",
                displayName: "Rick Zabel",
                normName: "rick-zabel",
                nationality: "Germany",
                team: "team-katusha-alpecin",
                pageUrl: "https://www.procyclingstats.com/rider/rick-zabel",
                age: "24",
                height: "1.84",
                weight: "72",
                grandTours: 4,
                classicRaces: 7,
                proWins: 1,
                sportRadarId: "sr:rider:135926",
            },
            {
                _id: "5bee8eb781239eae881f27e6",
                displayName: "Lawson Craddock",
                normName: "lawson-craddock",
                nationality: "United",
                team: "team-ef-education-first-drapac-p-b-cannondale",
                pageUrl: "https://www.procyclingstats.com/rider/lawson-craddock",
                age: "26",
                height: "1.78",
                weight: "69",
                grandTours: 4,
                classicRaces: 5,
                proWins: 0,
                sportRadarId: "sr:rider:146102",
            },
            {
                _id: "5bee8eb781239eae881f287b",
                displayName: "Jasper Stuyven",
                normName: "jasper-stuyven",
                nationality: "Belgium",
                team: "trek-segafredo",
                pageUrl: "https://www.procyclingstats.com/rider/jasper-stuyven",
                age: "26",
                height: "1.86",
                weight: "78",
                grandTours: 5,
                classicRaces: 13,
                proWins: 6,
                sportRadarId: "sr:rider:146106",
            },
            {
                _id: "5bee8eb781239eae881f2861",
                displayName: "Chad Haga",
                normName: "chad-haga",
                nationality: "United",
                team: "team-sunweb",
                pageUrl: "https://www.procyclingstats.com/rider/chad-haga",
                age: "30",
                height: "1.91",
                weight: "71.5",
                grandTours: 8,
                classicRaces: 4,
                proWins: 1,
                sportRadarId: "sr:rider:146340",
            },
            {
                _id: "5bee8eb781239eae881f271a",
                displayName: "Paweł Poljański",
                normName: "pawel-poljanski",
                nationality: "Poland",
                team: "bora-hansgrohe",
                pageUrl: "https://www.procyclingstats.com/rider/pawel-poljanski",
                age: "28",
                height: null,
                weight: null,
                grandTours: 6,
                classicRaces: 7,
                proWins: 0,
                sportRadarId: "sr:rider:146348",
            },
            {
                _id: "5bee8eb781239eae881f26b5",
                displayName: "Silvan Dillier",
                normName: "silvan-dillier",
                nationality: "Switzerland",
                team: "ag2r-la-mondiale",
                pageUrl: "https://www.procyclingstats.com/rider/silvan-dillier",
                age: "28",
                height: "1.83",
                weight: "75",
                grandTours: 5,
                classicRaces: 8,
                proWins: 7,
                sportRadarId: "sr:rider:147008",
            },
            {
                _id: "5bee8eb781239eae881f285e",
                displayName: "Edward Theuns",
                normName: "edward-theuns",
                nationality: "Belgium",
                team: "team-sunweb",
                pageUrl: "https://www.procyclingstats.com/rider/edward-theuns",
                age: "27",
                height: "1.83",
                weight: "72",
                grandTours: 3,
                classicRaces: 11,
                proWins: 7,
                sportRadarId: "sr:rider:148206",
            },
            {
                _id: "5bee8eb781239eae881f2768",
                displayName: "Jasper de Buyst",
                normName: "jasper-de-buyst",
                nationality: "Belgium",
                team: "lotto-soudal",
                pageUrl: "https://www.procyclingstats.com/rider/jasper-de-buyst",
                age: "24",
                height: "1.78",
                weight: "69",
                grandTours: 3,
                classicRaces: 5,
                proWins: 4,
                sportRadarId: "sr:rider:171236",
            },
            {
                _id: "5bee8eb781239eae881f2739",
                displayName: "Olivier Le Gac",
                normName: "olivier-le-gac",
                nationality: "France",
                team: "groupama-fdj",
                pageUrl: "https://www.procyclingstats.com/rider/olivier-le-gac",
                age: "25",
                height: "1.8",
                weight: "70",
                grandTours: 4,
                classicRaces: 8,
                proWins: 1,
                sportRadarId: "sr:rider:179078",
            },
            {
                _id: "5bee8eb781239eae881f281e",
                displayName: "Timo Roosen",
                normName: "timo-roosen",
                nationality: "Netherlands",
                team: "team-lottonl-jumbo",
                pageUrl: "https://www.procyclingstats.com/rider/timo-roosen",
                age: "25",
                height: "1.94",
                weight: "75",
                grandTours: 4,
                classicRaces: 5,
                proWins: 2,
                sportRadarId: "sr:rider:189358",
            },
            {
                _id: "5bee8eb781239eae881f2a32",
                displayName: "Kévin Ledanois",
                normName: "kevin-ledanois",
                nationality: "France",
                team: "fortuneo-samsic",
                pageUrl: "https://www.procyclingstats.com/rider/kevin-ledanois",
                age: "25",
                height: "1.81",
                weight: "62",
                grandTours: 1,
                classicRaces: 3,
                proWins: 0,
                sportRadarId: "sr:rider:196754",
            },
            {
                _id: "5bee8eb781239eae881f26ac",
                displayName: "Pierre Latour",
                normName: "pierre-latour",
                nationality: "France",
                team: "ag2r-la-mondiale",
                pageUrl: "https://www.procyclingstats.com/rider/pierre-latour",
                age: "25",
                height: "1.8",
                weight: "64",
                grandTours: 3,
                classicRaces: 4,
                proWins: 4,
                sportRadarId: "sr:rider:196756",
            },
            {
                _id: "5bee8eb781239eae881f279d",
                displayName: "Marc Soler",
                normName: "marc-soler",
                nationality: "Spain",
                team: "movistar-team",
                pageUrl: "https://www.procyclingstats.com/rider/marc-soler",
                age: "24",
                height: "1.86",
                weight: "68",
                grandTours: 2,
                classicRaces: 5,
                proWins: 2,
                sportRadarId: "sr:rider:196762",
            },
            {
                _id: "5bee8eb781239eae881f27de",
                displayName: "Daniel Felipe Martínez",
                normName: "daniel-felipe-martinez",
                nationality: "Colombia",
                team: "team-ef-education-first-drapac-p-b-cannondale",
                pageUrl: "https://www.procyclingstats.com/rider/daniel-felipe-martinez",
                age: "22",
                height: "1.74",
                weight: "63",
                grandTours: 3,
                classicRaces: 7,
                proWins: 0,
                sportRadarId: "sr:rider:196772",
            },
            {
                _id: "5bee8eb781239eae881f2756",
                displayName: "Tiesj Benoot",
                normName: "tiesj-benoot",
                nationality: "Belgium",
                team: "lotto-soudal",
                pageUrl: "https://www.procyclingstats.com/rider/tiesj-benoot",
                age: "24",
                height: "1.9",
                weight: "72",
                grandTours: 3,
                classicRaces: 11,
                proWins: 1,
                sportRadarId: "sr:rider:197808",
            },
            {
                _id: "5bee8eb781239eae881f292d",
                displayName: "Anthony Turgis",
                normName: "anthony-turgis",
                nationality: "France",
                team: "cofidis-solutions-credits",
                pageUrl: "https://www.procyclingstats.com/rider/anthony-turgis",
                age: "24",
                height: "1.79",
                weight: "69",
                grandTours: 2,
                classicRaces: 4,
                proWins: 4,
                sportRadarId: "sr:rider:198994",
            },
            {
                _id: "5bee8eb781239eae881f26f8",
                displayName: "Stefan Küng",
                normName: "stefan-kung",
                nationality: "Switzerland",
                team: "bmc-racing-team",
                pageUrl: "https://www.procyclingstats.com/rider/stefan-kung",
                age: "25",
                height: "1.93",
                weight: "83",
                grandTours: 4,
                classicRaces: 7,
                proWins: 8,
                sportRadarId: "sr:rider:199422",
            },
            {
                _id: "5bee8eb781239eae881f291d",
                displayName: "Christophe Laporte",
                normName: "christophe-laporte",
                nationality: "France",
                team: "cofidis-solutions-credits",
                pageUrl: "https://www.procyclingstats.com/rider/christophe-laporte",
                age: "25",
                height: "1.89",
                weight: "76",
                grandTours: 4,
                classicRaces: 10,
                proWins: 8,
                sportRadarId: "sr:rider:208169",
            },
            {
                _id: "5bee8eb781239eae881f281b",
                displayName: "Dylan Groenewegen",
                normName: "dylan-groenewegen",
                nationality: "Netherlands",
                team: "team-lottonl-jumbo",
                pageUrl: "https://www.procyclingstats.com/rider/dylan-groenewegen",
                age: "25",
                height: "1.77",
                weight: "70",
                grandTours: 3,
                classicRaces: 3,
                proWins: 35,
                sportRadarId: "sr:rider:219922",
            },
            {
                _id: "5bee8eb781239eae881f294d",
                displayName: "Thomas Boudat",
                normName: "thomas-boudat",
                nationality: "France",
                team: "direct-energie",
                pageUrl: "https://www.procyclingstats.com/rider/thomas-boudat",
                age: "24",
                height: "1.75",
                weight: "67",
                grandTours: 2,
                classicRaces: 0,
                proWins: 4,
                sportRadarId: "sr:rider:222626",
            },
            {
                _id: "5bee8eb781239eae881f2888",
                displayName: "Toms Skujiņš",
                normName: "toms-skujins",
                nationality: "Latvia",
                team: "trek-segafredo",
                pageUrl: "https://www.procyclingstats.com/rider/toms-skujins",
                age: "27",
                height: "1.78",
                weight: "70",
                grandTours: 2,
                classicRaces: 6,
                proWins: 7,
                sportRadarId: "sr:rider:226716",
            },
            {
                _id: "5bee8eb781239eae881f2713",
                displayName: "Lukas Pöstlberger",
                normName: "lukas-postlberger",
                nationality: "Austria",
                team: "bora-hansgrohe",
                pageUrl: "https://www.procyclingstats.com/rider/lukas-postlberger",
                age: "26",
                height: "1.82",
                weight: "70",
                grandTours: 3,
                classicRaces: 3,
                proWins: 4,
                sportRadarId: "sr:rider:226826",
            },
            {
                _id: "5bee8eb781239eae881f27a6",
                displayName: "Maximiliano Richeze",
                normName: "ariel-maximiliano-richeze",
                nationality: "Argentina",
                team: "quick-step-floors",
                pageUrl: "https://www.procyclingstats.com/rider/ariel-maximiliano-richeze",
                age: "35",
                height: "1.75",
                weight: "68",
                grandTours: 10,
                classicRaces: 10,
                proWins: 15,
                sportRadarId: "sr:rider:226972",
            },
            {
                _id: "5bee8eb781239eae881f26fe",
                displayName: "Patrick Bevin",
                normName: "patrick-bevin",
                nationality: "New",
                team: "bmc-racing-team",
                pageUrl: "https://www.procyclingstats.com/rider/patrick-bevin",
                age: "27",
                height: "1.8",
                weight: "75",
                grandTours: 3,
                classicRaces: 1,
                proWins: 4,
                sportRadarId: "sr:rider:241178",
            },
            {
                _id: "5bee8eb781239eae881f2876",
                displayName: "Michael Gogl",
                normName: "michael-gogl",
                nationality: "Austria",
                team: "trek-segafredo",
                pageUrl: "https://www.procyclingstats.com/rider/michael-gogl",
                age: "25",
                height: "1.86",
                weight: "70",
                grandTours: 3,
                classicRaces: 6,
                proWins: 0,
                sportRadarId: "sr:rider:241192",
            },
            {
                _id: "5bee8eb781239eae881f2817",
                displayName: "Primož Roglič",
                normName: "primoz-roglic",
                nationality: "Slovenia",
                team: "team-lottonl-jumbo",
                pageUrl: "https://www.procyclingstats.com/rider/primoz-roglic",
                age: "29",
                height: "1.77",
                weight: "65",
                grandTours: 3,
                classicRaces: 3,
                proWins: 22,
                sportRadarId: "sr:rider:241198",
            },
            {
                _id: "5bee8eb781239eae881f2957",
                displayName: "Lilian Calmejane",
                normName: "lilian-calmejane",
                nationality: "France",
                team: "direct-energie",
                pageUrl: "https://www.procyclingstats.com/rider/lilian-calmejane",
                age: "25",
                height: "1.84",
                weight: "69",
                grandTours: 3,
                classicRaces: 4,
                proWins: 10,
                sportRadarId: "sr:rider:246981",
            },
            {
                _id: "5bee8eb781239eae881f27ba",
                displayName: "Fernando Gaviria",
                normName: "fernando-gaviria",
                nationality: "Colombia",
                team: "quick-step-floors",
                pageUrl: "https://www.procyclingstats.com/rider/fernando-gaviria",
                age: "24",
                height: "1.8",
                weight: "71",
                grandTours: 2,
                classicRaces: 2,
                proWins: 34,
                sportRadarId: "sr:rider:247359",
            },
            {
                _id: "5bee8eb781239eae881f272a",
                displayName: "Gregor Mühlberger",
                normName: "gregor-muhlberger",
                nationality: "Austria",
                team: "bora-hansgrohe",
                pageUrl: "https://www.procyclingstats.com/rider/gregor-muhlberger",
                age: "24",
                height: "1.8",
                weight: "64",
                grandTours: 3,
                classicRaces: 5,
                proWins: 3,
                sportRadarId: "sr:rider:247361",
            },
            {
                _id: "5bee8eb781239eae881f2819",
                displayName: "Antwan Tolhoek",
                normName: "antwan-tolhoek",
                nationality: "Netherlands",
                team: "team-lottonl-jumbo",
                pageUrl: "https://www.procyclingstats.com/rider/antwan-tolhoek",
                age: "24",
                height: "1.78",
                weight: "61",
                grandTours: 2,
                classicRaces: 4,
                proWins: 0,
                sportRadarId: "sr:rider:248851",
            },
            {
                _id: "5bee8eb781239eae881f2886",
                displayName: "Julien Bernard",
                normName: "julien-bernard",
                nationality: "France",
                team: "trek-segafredo",
                pageUrl: "https://www.procyclingstats.com/rider/julien-bernard",
                age: "26",
                height: "1.76",
                weight: "60",
                grandTours: 4,
                classicRaces: 3,
                proWins: 0,
                sportRadarId: "sr:rider:248863",
            },
            {
                _id: "5bee8eb781239eae881f2812",
                displayName: "Nils Politt",
                normName: "nils-politt",
                nationality: "Germany",
                team: "team-katusha-alpecin",
                pageUrl: "https://www.procyclingstats.com/rider/nils-politt",
                age: "24",
                height: "1.92",
                weight: "80",
                grandTours: 2,
                classicRaces: 7,
                proWins: 1,
                sportRadarId: "sr:rider:249457",
            },
            {
                _id: "5bee8eb781239eae881f2921",
                displayName: "Dimitri Claeys",
                normName: "dimitri-claeys",
                nationality: "Belgium",
                team: "cofidis-solutions-credits",
                pageUrl: "https://www.procyclingstats.com/rider/dimitri-claeys",
                age: "31",
                height: "1.89",
                weight: "77",
                grandTours: 2,
                classicRaces: 5,
                proWins: 4,
                sportRadarId: "sr:rider:249475",
            },
            {
                _id: "5bee8eb781239eae881f2833",
                displayName: "Gianni Moscon",
                normName: "gianni-moscon",
                nationality: "Italy",
                team: "team-sky",
                pageUrl: "https://www.procyclingstats.com/rider/gianni-moscon",
                age: "24",
                height: "1.82",
                weight: "70",
                grandTours: 2,
                classicRaces: 11,
                proWins: 8,
                sportRadarId: "sr:rider:250457",
            },
            {
                _id: "5bee8eb781239eae881f2a8f",
                displayName: "Guillaume Martin",
                normName: "guillaume-martin",
                nationality: "France",
                team: "wanty-groupe-gobert",
                pageUrl: "https://www.procyclingstats.com/rider/guillaume-martin",
                age: "25",
                height: "1.73",
                weight: "55",
                grandTours: 2,
                classicRaces: 3,
                proWins: 5,
                sportRadarId: "sr:rider:254335",
            },
            {
                _id: "5bee8eb781239eae881f26f3",
                displayName: "Franco Pellizotti",
                normName: "franco-pellizotti",
                nationality: "Italy",
                team: "bahrain-merida-pro-cycling-team",
                pageUrl: "https://www.procyclingstats.com/rider/franco-pellizotti",
                age: "40",
                height: "1.75",
                weight: "64",
                grandTours: 19,
                classicRaces: 33,
                proWins: 12,
                sportRadarId: "sr:rider:26425",
            },
            {
                _id: "5bee8eb781239eae881f278c",
                displayName: "Daniele Bennati",
                normName: "daniele-bennati",
                nationality: "Italy",
                team: "movistar-team",
                pageUrl: "https://www.procyclingstats.com/rider/daniele-bennati",
                age: "38",
                height: "1.83",
                weight: "71",
                grandTours: 25,
                classicRaces: 27,
                proWins: 51,
                sportRadarId: "sr:rider:26451",
            },
            {
                _id: "5bee8eb781239eae881f295d",
                displayName: "Sylvain Chavanel",
                normName: "sylvain-chavanel",
                nationality: "France",
                team: "direct-energie",
                pageUrl: "https://www.procyclingstats.com/rider/sylvain-chavanel",
                age: "39",
                height: "1.81",
                weight: "73",
                grandTours: 23,
                classicRaces: 44,
                proWins: 45,
                sportRadarId: "sr:rider:26463",
            },
            {
                _id: "5bee8eb781239eae881f27a3",
                displayName: "Philippe Gilbert",
                normName: "philippe-gilbert",
                nationality: "Belgium",
                team: "quick-step-floors",
                pageUrl: "https://www.procyclingstats.com/rider/philippe-gilbert",
                age: "36",
                height: "1.79",
                weight: "69",
                grandTours: 21,
                classicRaces: 51,
                proWins: 73,
                sportRadarId: "sr:rider:26544",
            },
            {
                _id: "5bee8eb781239eae881f279b",
                displayName: "Alejandro Valverde",
                normName: "alejandro-valverde",
                nationality: "Spain",
                team: "movistar-team",
                pageUrl: "https://www.procyclingstats.com/rider/alejandro-valverde",
                age: "38",
                height: "1.78",
                weight: "61",
                grandTours: 24,
                classicRaces: 27,
                proWins: 122,
                sportRadarId: "sr:rider:26658",
            },
            {
                _id: "5bee8eb781239eae881f26c6",
                displayName: "Luis León Sánchez",
                normName: "luis-leon-sanchez",
                nationality: "Spain",
                team: "astana-pro-team",
                pageUrl: "https://www.procyclingstats.com/rider/luis-leon-sanchez",
                age: "34",
                height: "1.87",
                weight: "74",
                grandTours: 20,
                classicRaces: 20,
                proWins: 38,
                sportRadarId: "sr:rider:26697",
            },
            {
                _id: "5bee8eb781239eae881f27c9",
                displayName: "Mark Renshaw",
                normName: "mark-renshaw",
                nationality: "Australia",
                team: "team-dimension-data",
                pageUrl: "https://www.procyclingstats.com/rider/mark-renshaw",
                age: "36",
                height: "1.79",
                weight: "72",
                grandTours: 16,
                classicRaces: 18,
                proWins: 12,
                sportRadarId: "sr:rider:26738",
            },
            {
                _id: "5bee8eb781239eae881f26e5",
                displayName: "Vincenzo Nibali",
                normName: "vincenzo-nibali",
                nationality: "Italy",
                team: "bahrain-merida-pro-cycling-team",
                pageUrl: "https://www.procyclingstats.com/rider/vincenzo-nibali",
                age: "34",
                height: "1.81",
                weight: "65",
                grandTours: 20,
                classicRaces: 35,
                proWins: 51,
                sportRadarId: "sr:rider:26792",
            },
            {
                _id: "5bee8eb781239eae881f26e9",
                displayName: "Heinrich Haussler",
                normName: "heinrich-haussler",
                nationality: "Australia",
                team: "bahrain-merida-pro-cycling-team",
                pageUrl: "https://www.procyclingstats.com/rider/heinrich-haussler",
                age: "34",
                height: "1.81",
                weight: "74",
                grandTours: 11,
                classicRaces: 34,
                proWins: 22,
                sportRadarId: "sr:rider:26800",
            },
            {
                _id: "5bee8eb781239eae881f287e",
                displayName: "Koen de Kort",
                normName: "koen-de-kort",
                nationality: "Netherlands",
                team: "trek-segafredo",
                pageUrl: "https://www.procyclingstats.com/rider/koen-de-kort",
                age: "36",
                height: "1.79",
                weight: "69",
                grandTours: 15,
                classicRaces: 36,
                proWins: 1,
                sportRadarId: "sr:rider:26822",
            },
            {
                _id: "5bee8eb781239eae881f2919",
                displayName: "Daniel Navarro",
                normName: "daniel-navarro",
                nationality: "Spain",
                team: "cofidis-solutions-credits",
                pageUrl: "https://www.procyclingstats.com/rider/daniel-navarro",
                age: "35",
                height: "1.75",
                weight: "60",
                grandTours: 17,
                classicRaces: 5,
                proWins: 4,
                sportRadarId: "sr:rider:26824",
            },
            {
                _id: "5bee8eb781239eae881f2770",
                displayName: "Mathew Hayman",
                normName: "mathew-hayman",
                nationality: "Australia",
                team: "mitchelton-scott",
                pageUrl: "https://www.procyclingstats.com/rider/mathew-hayman",
                age: "40",
                height: "1.9",
                weight: "78",
                grandTours: 11,
                classicRaces: 41,
                proWins: 3,
                sportRadarId: "sr:rider:26833",
            },
            {
                _id: "5bee8eb781239eae881f288c",
                displayName: "Rory Sutherland",
                normName: "rory-sutherland",
                nationality: "Australia",
                team: "uae-team-emirates",
                pageUrl: "https://www.procyclingstats.com/rider/rory-sutherland",
                age: "36",
                height: "1.88",
                weight: "75",
                grandTours: 7,
                classicRaces: 7,
                proWins: 3,
                sportRadarId: "sr:rider:26834",
            },
            {
                _id: "5bee8eb781239eae881f26e0",
                displayName: "Domenico Pozzovivo",
                normName: "domenico-pozzovivo",
                nationality: "Italy",
                team: "bahrain-merida-pro-cycling-team",
                pageUrl: "https://www.procyclingstats.com/rider/domenico-pozzovivo",
                age: "35",
                height: "1.65",
                weight: "53",
                grandTours: 17,
                classicRaces: 21,
                proWins: 13,
                sportRadarId: "sr:rider:26878",
            },
            {
                _id: "5bee8eb781239eae881f2701",
                displayName: "Simon Gerrans",
                normName: "simon-gerrans",
                nationality: "Australia",
                team: "bmc-racing-team",
                pageUrl: "https://www.procyclingstats.com/rider/simon-gerrans",
                age: "38",
                height: "1.69",
                weight: "62",
                grandTours: 19,
                classicRaces: 22,
                proWins: 33,
                sportRadarId: "sr:rider:26897",
            },
            {
                _id: "5bee8eb781239eae881f2797",
                displayName: "Imanol Erviti",
                normName: "imanol-erviti",
                nationality: "Spain",
                team: "movistar-team",
                pageUrl: "https://www.procyclingstats.com/rider/imanol-erviti",
                age: "35",
                height: "1.89",
                weight: "75",
                grandTours: 21,
                classicRaces: 46,
                proWins: 3,
                sportRadarId: "sr:rider:26931",
            },
            {
                _id: "5bee8eb781239eae881f2858",
                displayName: "Laurens ten Dam",
                normName: "laurens-ten-dam",
                nationality: "Netherlands",
                team: "team-sunweb",
                pageUrl: "https://www.procyclingstats.com/rider/laurens-ten-dam",
                age: "38",
                height: "1.84",
                weight: "69",
                grandTours: 17,
                classicRaces: 15,
                proWins: 2,
                sportRadarId: "sr:rider:26945",
            },
            {
                _id: "5bee8eb781239eae881f2755",
                displayName: "André Greipel",
                normName: "andre-greipel",
                nationality: "Germany",
                team: "lotto-soudal",
                pageUrl: "https://www.procyclingstats.com/rider/andre-greipel",
                age: "36",
                height: "1.84",
                weight: "75",
                grandTours: 16,
                classicRaces: 21,
                proWins: 155,
                sportRadarId: "sr:rider:26973",
            },
            {
                _id: "5bee8eb781239eae881f2a9b",
                displayName: "Dion Smith",
                normName: "dion-smith",
                nationality: "New",
                team: "wanty-groupe-gobert",
                pageUrl: "https://www.procyclingstats.com/rider/dion-smith",
                age: "25",
                height: "1.79",
                weight: "67",
                grandTours: 2,
                classicRaces: 4,
                proWins: 0,
                sportRadarId: "sr:rider:270495",
            },
            {
                _id: "5bee8eb781239eae881f2a2e",
                displayName: "Amaël Moinard",
                normName: "amael-moinard",
                nationality: "France",
                team: "fortuneo-samsic",
                pageUrl: "https://www.procyclingstats.com/rider/amael-moinard",
                age: "36",
                height: "1.8",
                weight: "69",
                grandTours: 16,
                classicRaces: 15,
                proWins: 3,
                sportRadarId: "sr:rider:27050",
            },
            {
                _id: "5bee8eb781239eae881f271b",
                displayName: "Marcus Burghardt",
                normName: "marcus-burghardt",
                nationality: "Germany",
                team: "bora-hansgrohe",
                pageUrl: "https://www.procyclingstats.com/rider/marcus-burghardt",
                age: "35",
                height: "1.89",
                weight: "75",
                grandTours: 14,
                classicRaces: 36,
                proWins: 7,
                sportRadarId: "sr:rider:27072",
            },
            {
                _id: "5bee8eb781239eae881f279f",
                displayName: "José Joaquín Rojas",
                normName: "jose-joaquin-rojas",
                nationality: "Spain",
                team: "movistar-team",
                pageUrl: "https://www.procyclingstats.com/rider/jose-joaquin-rojas",
                age: "33",
                height: "1.79",
                weight: "69",
                grandTours: 14,
                classicRaces: 34,
                proWins: 10,
                sportRadarId: "sr:rider:27252",
            },
            {
                _id: "5bee8eb781239eae881f27f2",
                displayName: "Rigoberto Urán",
                normName: "rigoberto-uran",
                nationality: "Colombia",
                team: "team-ef-education-first-drapac-p-b-cannondale",
                pageUrl: "https://www.procyclingstats.com/rider/rigoberto-uran",
                age: "31",
                height: "1.73",
                weight: "63",
                grandTours: 16,
                classicRaces: 17,
                proWins: 13,
                sportRadarId: "sr:rider:27345",
            },
            {
                _id: "5bee8eb781239eae881f281c",
                displayName: "Paul Martens",
                normName: "paul-martens",
                nationality: "Germany",
                team: "team-lottonl-jumbo",
                pageUrl: "https://www.procyclingstats.com/rider/paul-martens",
                age: "35",
                height: "1.78",
                weight: "69",
                grandTours: 9,
                classicRaces: 23,
                proWins: 8,
                sportRadarId: "sr:rider:27347",
            },
            {
                _id: "5bee8eb781239eae881f27d4",
                displayName: "Serge Pauwels",
                normName: "serge-pauwels",
                nationality: "Belgium",
                team: "team-dimension-data",
                pageUrl: "https://www.procyclingstats.com/rider/serge-pauwels",
                age: "34",
                height: "1.78",
                weight: "65",
                grandTours: 12,
                classicRaces: 18,
                proWins: 3,
                sportRadarId: "sr:rider:27412",
            },
            {
                _id: "5bee8eb781239eae881f2760",
                displayName: "Marcel Sieberg",
                normName: "marcel-sieberg",
                nationality: "Germany",
                team: "lotto-soudal",
                pageUrl: "https://www.procyclingstats.com/rider/marcel-sieberg",
                age: "36",
                height: "1.98",
                weight: "80",
                grandTours: 11,
                classicRaces: 31,
                proWins: 2,
                sportRadarId: "sr:rider:27484",
            },
            {
                _id: "5bee8eb781239eae881f2759",
                displayName: "Tomasz Marczyński",
                normName: "tomasz-marczynski",
                nationality: "Poland",
                team: "lotto-soudal",
                pageUrl: "https://www.procyclingstats.com/rider/tomasz-marczynski",
                age: "34",
                height: "1.8",
                weight: "69",
                grandTours: 6,
                classicRaces: 7,
                proWins: 8,
                sportRadarId: "sr:rider:27510",
            },
            {
                _id: "5bee8eb781239eae881f27c5",
                displayName: "Mark Cavendish",
                normName: "mark-cavendish",
                nationality: "Great",
                team: "team-dimension-data",
                pageUrl: "https://www.procyclingstats.com/rider/mark-cavendish",
                age: "33",
                height: "1.75",
                weight: "70",
                grandTours: 19,
                classicRaces: 14,
                proWins: 146,
                sportRadarId: "sr:rider:27617",
            },
            {
                _id: "5bee8eb781239eae881f2704",
                displayName: "Greg Van Avermaet",
                normName: "greg-van-avermaet",
                nationality: "Belgium",
                team: "bmc-racing-team",
                pageUrl: "https://www.procyclingstats.com/rider/greg-van-avermaet",
                age: "33",
                height: "1.81",
                weight: "74",
                grandTours: 9,
                classicRaces: 41,
                proWins: 38,
                sportRadarId: "sr:rider:27623",
            },
            {
                _id: "5bee8eb781239eae881f27eb",
                displayName: "Pierre Rolland",
                normName: "pierre-rolland",
                nationality: "France",
                team: "team-ef-education-first-drapac-p-b-cannondale",
                pageUrl: "https://www.procyclingstats.com/rider/pierre-rolland",
                age: "32",
                height: "1.84",
                weight: "67",
                grandTours: 16,
                classicRaces: 8,
                proWins: 11,
                sportRadarId: "sr:rider:27645",
            },
            {
                _id: "5bee8eb781239eae881f27af",
                displayName: "Niki Terpstra",
                normName: "niki-terpstra",
                nationality: "Netherlands",
                team: "quick-step-floors",
                pageUrl: "https://www.procyclingstats.com/rider/niki-terpstra",
                age: "34",
                height: "1.88",
                weight: "75",
                grandTours: 13,
                classicRaces: 30,
                proWins: 22,
                sportRadarId: "sr:rider:27654",
            },
            {
                _id: "5bee8eb781239eae881f2825",
                displayName: "Robert Gesink",
                normName: "robert-gesink",
                nationality: "Netherlands",
                team: "team-lottonl-jumbo",
                pageUrl: "https://www.procyclingstats.com/rider/robert-gesink",
                age: "32",
                height: "1.89",
                weight: "70",
                grandTours: 15,
                classicRaces: 14,
                proWins: 13,
                sportRadarId: "sr:rider:27656",
            },
            {
                _id: "5bee8eb781239eae881f27e8",
                displayName: "Simon Clarke",
                normName: "simon-clarke",
                nationality: "Australia",
                team: "team-ef-education-first-drapac-p-b-cannondale",
                pageUrl: "https://www.procyclingstats.com/rider/simon-clarke",
                age: "32",
                height: "1.75",
                weight: "63",
                grandTours: 12,
                classicRaces: 20,
                proWins: 5,
                sportRadarId: "sr:rider:27667",
            },
            {
                _id: "5bee8eb781239eae881f2897",
                displayName: "Marco Marcato",
                normName: "marco-marcato",
                nationality: "Italy",
                team: "uae-team-emirates",
                pageUrl: "https://www.procyclingstats.com/rider/marco-marcato",
                age: "34",
                height: "1.74",
                weight: "67",
                grandTours: 9,
                classicRaces: 30,
                proWins: 5,
                sportRadarId: "sr:rider:27688",
            },
            {
                _id: "5bee8eb781239eae881f2898",
                displayName: "Roberto Ferrari",
                normName: "roberto-ferrari",
                nationality: "Italy",
                team: "uae-team-emirates",
                pageUrl: "https://www.procyclingstats.com/rider/roberto-ferrari",
                age: "35",
                height: "1.73",
                weight: "73",
                grandTours: 10,
                classicRaces: 10,
                proWins: 11,
                sportRadarId: "sr:rider:27692",
            },
            {
                _id: "5bee8eb781239eae881f275d",
                displayName: "Jelle Vanendert",
                normName: "jelle-vanendert",
                nationality: "Belgium",
                team: "lotto-soudal",
                pageUrl: "https://www.procyclingstats.com/rider/jelle-vanendert",
                age: "33",
                height: "1.84",
                weight: "62",
                grandTours: 9,
                classicRaces: 20,
                proWins: 2,
                sportRadarId: "sr:rider:27728",
            },
            {
                _id: "5bee8eb781239eae881f26d3",
                displayName: "Jakob Fuglsang",
                normName: "jakob-fuglsang",
                nationality: "Denmark",
                team: "astana-pro-team",
                pageUrl: "https://www.procyclingstats.com/rider/jakob-fuglsang",
                age: "33",
                height: "1.82",
                weight: "68",
                grandTours: 12,
                classicRaces: 16,
                proWins: 17,
                sportRadarId: "sr:rider:27770",
            },
            {
                _id: "5bee8eb781239eae881f2717",
                displayName: "Maciej Bodnar",
                normName: "maciej-bodnar",
                nationality: "Poland",
                team: "bora-hansgrohe",
                pageUrl: "https://www.procyclingstats.com/rider/maciej-bodnar",
                age: "33",
                height: "1.86",
                weight: "70",
                grandTours: 12,
                classicRaces: 22,
                proWins: 8,
                sportRadarId: "sr:rider:27810",
            },
            {
                _id: "5bee8eb781239eae881f28a6",
                displayName: "Kristijan Đurasek",
                normName: "kristijan-durasek",
                nationality: "Croatia",
                team: "uae-team-emirates",
                pageUrl: "https://www.procyclingstats.com/rider/kristijan-durasek",
                age: "31",
                height: "1.7",
                weight: "56",
                grandTours: 8,
                classicRaces: 5,
                proWins: 6,
                sportRadarId: "sr:rider:27847",
            },
            {
                _id: "5bee8eb781239eae881f276c",
                displayName: "Daryl Impey",
                normName: "daryl-impey",
                nationality: "South",
                team: "mitchelton-scott",
                pageUrl: "https://www.procyclingstats.com/rider/daryl-impey",
                age: "33",
                height: "1.81",
                weight: "70",
                grandTours: 8,
                classicRaces: 18,
                proWins: 22,
                sportRadarId: "sr:rider:27851",
            },
            {
                _id: "5bee8eb781239eae881f27ff",
                displayName: "Robert Kišerlovski",
                normName: "robert-kiserlovski",
                nationality: "Croatia",
                team: "team-katusha-alpecin",
                pageUrl: "https://www.procyclingstats.com/rider/robert-kiserlovski",
                age: "32",
                height: "1.8",
                weight: "72",
                grandTours: 13,
                classicRaces: 7,
                proWins: 2,
                sportRadarId: "sr:rider:27853",
            },
            {
                _id: "5bee8eb781239eae881f26c5",
                displayName: "Tanel Kangert",
                normName: "tanel-kangert",
                nationality: "Estonia",
                team: "astana-pro-team",
                pageUrl: "https://www.procyclingstats.com/rider/tanel-kangert",
                age: "31",
                height: "1.78",
                weight: "65",
                grandTours: 13,
                classicRaces: 6,
                proWins: 11,
                sportRadarId: "sr:rider:27883",
            },
            {
                _id: "5bee8eb781239eae881f27d0",
                displayName: "Edvald Boasson Hagen",
                normName: "edvald-boasson-hagen",
                nationality: "Norway",
                team: "team-dimension-data",
                pageUrl: "https://www.procyclingstats.com/rider/edvald-boasson-hagen",
                age: "31",
                height: "1.85",
                weight: "75",
                grandTours: 11,
                classicRaces: 28,
                proWins: 72,
                sportRadarId: "sr:rider:27884",
            },
            {
                _id: "5bee8eb781239eae881f2814",
                displayName: "Tony Martin",
                normName: "tony-martin",
                nationality: "Germany",
                team: "team-katusha-alpecin",
                pageUrl: "https://www.procyclingstats.com/rider/tony-martin",
                age: "33",
                height: "1.85",
                weight: "75",
                grandTours: 16,
                classicRaces: 10,
                proWins: 65,
                sportRadarId: "sr:rider:27886",
            },
            {
                _id: "5bee8eb781239eae881f2877",
                displayName: "Bauke Mollema",
                normName: "bauke-mollema",
                nationality: "Netherlands",
                team: "trek-segafredo",
                pageUrl: "https://www.procyclingstats.com/rider/bauke-mollema",
                age: "31",
                height: "1.81",
                weight: "64",
                grandTours: 14,
                classicRaces: 17,
                proWins: 12,
                sportRadarId: "sr:rider:27895",
            },
            {
                _id: "5bee8eb781239eae881f295f",
                displayName: "Damien Gaudin",
                normName: "damien-gaudin",
                nationality: "France",
                team: "direct-energie",
                pageUrl: "https://www.procyclingstats.com/rider/damien-gaudin",
                age: "32",
                height: "1.9",
                weight: "82",
                grandTours: 5,
                classicRaces: 16,
                proWins: 6,
                sportRadarId: "sr:rider:27903",
            },
            {
                _id: "5bee8eb781239eae881f26a2",
                displayName: "Mathias Frank",
                normName: "mathias-frank",
                nationality: "Switzerland",
                team: "ag2r-la-mondiale",
                pageUrl: "https://www.procyclingstats.com/rider/mathias-frank",
                age: "31",
                height: "1.76",
                weight: "64",
                grandTours: 11,
                classicRaces: 14,
                proWins: 7,
                sportRadarId: "sr:rider:27907",
            },
            {
                _id: "5bee8eb781239eae881f2a9a",
                displayName: "Yoann Offredo",
                normName: "yoann-offredo",
                nationality: "France",
                team: "wanty-groupe-gobert",
                pageUrl: "https://www.procyclingstats.com/rider/yoann-offredo",
                age: "32",
                height: "1.89",
                weight: "68",
                grandTours: 3,
                classicRaces: 23,
                proWins: 1,
                sportRadarId: "sr:rider:27913",
            },
            {
                _id: "5bee8eb781239eae881f2963",
                displayName: "Rein Taaramäe",
                normName: "rein-taaramae",
                nationality: "Estonia",
                team: "direct-energie",
                pageUrl: "https://www.procyclingstats.com/rider/rein-taaramae",
                age: "31",
                height: "1.84",
                weight: "66",
                grandTours: 12,
                classicRaces: 9,
                proWins: 16,
                sportRadarId: "sr:rider:27916",
            },
            {
                _id: "5bee8eb781239eae881f2928",
                displayName: "Julien Simon",
                normName: "julien-simon",
                nationality: "France",
                team: "cofidis-solutions-credits",
                pageUrl: "https://www.procyclingstats.com/rider/julien-simon",
                age: "33",
                height: "1.76",
                weight: "65",
                grandTours: 7,
                classicRaces: 9,
                proWins: 9,
                sportRadarId: "sr:rider:27922",
            },
            {
                _id: "5bee8eb781239eae881f270e",
                displayName: "Richie Porte",
                normName: "richie-porte",
                nationality: "Australia",
                team: "bmc-racing-team",
                pageUrl: "https://www.procyclingstats.com/rider/richie-porte",
                age: "33",
                height: "1.72",
                weight: "62",
                grandTours: 13,
                classicRaces: 5,
                proWins: 29,
                sportRadarId: "sr:rider:27926",
            },
            {
                _id: "5bee8eb781239eae881f2a39",
                displayName: "Maxime Bouet",
                normName: "maxime-bouet",
                nationality: "France",
                team: "fortuneo-samsic",
                pageUrl: "https://www.procyclingstats.com/rider/maxime-bouet",
                age: "32",
                height: "1.84",
                weight: "67",
                grandTours: 13,
                classicRaces: 12,
                proWins: 5,
                sportRadarId: "sr:rider:27968",
            },
            {
                _id: "5bee8eb781239eae881f28a3",
                displayName: "Dan Martin",
                normName: "daniel-martin1",
                nationality: "Ireland",
                team: "uae-team-emirates",
                pageUrl: "https://www.procyclingstats.com/rider/daniel-martin1",
                age: "32",
                height: "1.75",
                weight: "59",
                grandTours: 13,
                classicRaces: 21,
                proWins: 20,
                sportRadarId: "sr:rider:27970",
            },
            {
                _id: "5bee8eb781239eae881f283c",
                displayName: "Chris Froome",
                normName: "christopher-froome",
                nationality: "Great",
                team: "team-sky",
                pageUrl: "https://www.procyclingstats.com/rider/christopher-froome",
                age: "33",
                height: null,
                weight: null,
                grandTours: 17,
                classicRaces: 7,
                proWins: 45,
                sportRadarId: "sr:rider:27990",
            },
            {
                _id: "5bee8eb781239eae881f2962",
                displayName: "Fabien Grellier",
                normName: "fabien-grellier",
                nationality: "France",
                team: "direct-energie",
                pageUrl: "https://www.procyclingstats.com/rider/fabien-grellier",
                age: "24",
                height: "1.8",
                weight: "64",
                grandTours: 1,
                classicRaces: 5,
                proWins: 0,
                sportRadarId: "sr:rider:282491",
            },
            {
                _id: "5bee8eb781239eae881f2a91",
                displayName: "Timothy Dupont",
                normName: "timothy-dupont",
                nationality: "Belgium",
                team: "wanty-groupe-gobert",
                pageUrl: "https://www.procyclingstats.com/rider/timothy-dupont",
                age: "31",
                height: "1.79",
                weight: "71",
                grandTours: 1,
                classicRaces: 0,
                proWins: 5,
                sportRadarId: "sr:rider:289025",
            },
            {
                _id: "5bee8eb781239eae881f27e3",
                displayName: "Tom Scully",
                normName: "thomas-scully",
                nationality: "New",
                team: "team-ef-education-first-drapac-p-b-cannondale",
                pageUrl: "https://www.procyclingstats.com/rider/thomas-scully",
                age: "28",
                height: "1.88",
                weight: "85",
                grandTours: 3,
                classicRaces: 5,
                proWins: 2,
                sportRadarId: "sr:rider:310616",
            },
            {
                _id: "5bee8eb781239eae881f2840",
                displayName: "Egan Bernal",
                normName: "egan-bernal",
                nationality: "Colombia",
                team: "team-sky",
                pageUrl: "https://www.procyclingstats.com/rider/egan-bernal",
                age: "21",
                height: "1.74",
                weight: "60",
                grandTours: 1,
                classicRaces: 2,
                proWins: 9,
                sportRadarId: "sr:rider:313921",
            },
            {
                _id: "5bee8eb781239eae881f289f",
                displayName: "Oliviero Troia",
                normName: "oliviero-troia",
                nationality: "Italy",
                team: "uae-team-emirates",
                pageUrl: "https://www.procyclingstats.com/rider/oliviero-troia",
                age: "24",
                height: "1.91",
                weight: "72",
                grandTours: 1,
                classicRaces: 5,
                proWins: 0,
                sportRadarId: "sr:rider:319259",
            },
            {
                _id: "5bee8eb781239eae881f274b",
                displayName: "David Gaudu",
                normName: "david-gaudu",
                nationality: "France",
                team: "groupama-fdj",
                pageUrl: "https://www.procyclingstats.com/rider/david-gaudu",
                age: "22",
                height: "1.73",
                weight: "53",
                grandTours: 1,
                classicRaces: 3,
                proWins: 1,
                sportRadarId: "sr:rider:323145",
            },
            {
                _id: "5bee8eb781239eae881f2923",
                displayName: "Anthony Perez",
                normName: "anthony-perez",
                nationality: "France",
                team: "cofidis-solutions-credits",
                pageUrl: "https://www.procyclingstats.com/rider/anthony-perez",
                age: "27",
                height: "1.9",
                weight: "70",
                grandTours: 2,
                classicRaces: 4,
                proWins: 2,
                sportRadarId: "sr:rider:325989",
            },
            {
                _id: "5bee8eb781239eae881f2a2a",
                displayName: "Élie Gesbert",
                normName: "elie-gesbert",
                nationality: "France",
                team: "fortuneo-samsic",
                pageUrl: "https://www.procyclingstats.com/rider/elie-gesbert",
                age: "23",
                height: "1.81",
                weight: "63",
                grandTours: 2,
                classicRaces: 2,
                proWins: 1,
                sportRadarId: "sr:rider:329997",
            },
            {
                _id: "5bee8eb781239eae881f2730",
                displayName: "Jacopo Guarnieri",
                normName: "jacopo-guarnieri",
                nationality: "Italy",
                team: "groupama-fdj",
                pageUrl: "https://www.procyclingstats.com/rider/jacopo-guarnieri",
                age: "31",
                height: "1.89",
                weight: "78",
                grandTours: 6,
                classicRaces: 22,
                proWins: 4,
                sportRadarId: "sr:rider:33025",
            },
            {
                _id: "5bee8eb781239eae881f2a96",
                displayName: "Marco Minnaard",
                normName: "marco-minnaard",
                nationality: "Netherlands",
                team: "wanty-groupe-gobert",
                pageUrl: "https://www.procyclingstats.com/rider/marco-minnaard",
                age: "29",
                height: "1.78",
                weight: "65",
                grandTours: 2,
                classicRaces: 5,
                proWins: 0,
                sportRadarId: "sr:rider:341226",
            },
            {
                _id: "5bee8eb781239eae881f279c",
                displayName: "Andrey Amador",
                normName: "andrey-amador",
                nationality: "Costa",
                team: "movistar-team",
                pageUrl: "https://www.procyclingstats.com/rider/andrey-amador",
                age: "32",
                height: "1.81",
                weight: "73",
                grandTours: 13,
                classicRaces: 16,
                proWins: 2,
                sportRadarId: "sr:rider:34405",
            },
            {
                _id: "5bee8eb781239eae881f272b",
                displayName: "Daniel Oss",
                normName: "daniel-oss",
                nationality: "Italy",
                team: "bora-hansgrohe",
                pageUrl: "https://www.procyclingstats.com/rider/daniel-oss",
                age: "31",
                height: "1.9",
                weight: "75",
                grandTours: 10,
                classicRaces: 25,
                proWins: 2,
                sportRadarId: "sr:rider:34406",
            },
            {
                _id: "5bee8eb781239eae881f2766",
                displayName: "Thomas De Gendt",
                normName: "thomas-de-gendt",
                nationality: "Belgium",
                team: "lotto-soudal",
                pageUrl: "https://www.procyclingstats.com/rider/thomas-de-gendt",
                age: "32",
                height: "1.77",
                weight: "69",
                grandTours: 14,
                classicRaces: 16,
                proWins: 13,
                sportRadarId: "sr:rider:35401",
            },
            {
                _id: "5bee8eb781239eae881f277e",
                displayName: "Mikel Nieve",
                normName: "mikel-nieve",
                nationality: "Spain",
                team: "mitchelton-scott",
                pageUrl: "https://www.procyclingstats.com/rider/mikel-nieve",
                age: "34",
                height: "1.73",
                weight: "62",
                grandTours: 16,
                classicRaces: 10,
                proWins: 5,
                sportRadarId: "sr:rider:35462",
            },
            {
                _id: "5bee8eb781239eae881f26de",
                displayName: "Gorka Izagirre",
                normName: "gorka-izagirre",
                nationality: "Spain",
                team: "bahrain-merida-pro-cycling-team",
                pageUrl: "https://www.procyclingstats.com/rider/gorka-izagirre",
                age: "31",
                height: "1.76",
                weight: "66.5",
                grandTours: 10,
                classicRaces: 12,
                proWins: 7,
                sportRadarId: "sr:rider:35470",
            },
            {
                _id: "5bee8eb781239eae881f26f9",
                displayName: "Tejay van Garderen",
                normName: "tejay-van-garderen",
                nationality: "United",
                team: "bmc-racing-team",
                pageUrl: "https://www.procyclingstats.com/rider/tejay-van-garderen",
                age: "30",
                height: "1.86",
                weight: "72",
                grandTours: 12,
                classicRaces: 6,
                proWins: 16,
                sportRadarId: "sr:rider:35498",
            },
            {
                _id: "5bee8eb781239eae881f2866",
                displayName: "Simon Geschke",
                normName: "simon-geschke",
                nationality: "Germany",
                team: "team-sunweb",
                pageUrl: "https://www.procyclingstats.com/rider/simon-geschke",
                age: "32",
                height: "1.7",
                weight: "64",
                grandTours: 12,
                classicRaces: 18,
                proWins: 3,
                sportRadarId: "sr:rider:35557",
            },
            {
                _id: "5bee8eb781239eae881f27c6",
                displayName: "Jay Robert Thomson",
                normName: "jay-robert-thomson",
                nationality: "South",
                team: "team-dimension-data",
                pageUrl: "https://www.procyclingstats.com/rider/jay-robert-thomson",
                age: "32",
                height: "1.85",
                weight: "75",
                grandTours: 4,
                classicRaces: 16,
                proWins: 4,
                sportRadarId: "sr:rider:38124",
            },
            {
                _id: "5bee8eb781239eae881f2954",
                displayName: "Romain Sicard",
                normName: "romain-sicard",
                nationality: "France",
                team: "direct-energie",
                pageUrl: "https://www.procyclingstats.com/rider/romain-sicard",
                age: "30",
                height: "1.77",
                weight: "64",
                grandTours: 10,
                classicRaces: 10,
                proWins: 1,
                sportRadarId: "sr:rider:39813",
            },
            {
                _id: "5bee8eb781239eae881f274c",
                displayName: "Arthur Vichot",
                normName: "arthur-vichot",
                nationality: "France",
                team: "groupama-fdj",
                pageUrl: "https://www.procyclingstats.com/rider/arthur-vichot",
                age: "29",
                height: "1.84",
                weight: "69",
                grandTours: 8,
                classicRaces: 14,
                proWins: 14,
                sportRadarId: "sr:rider:39818",
            },
            {
                _id: "5bee8eb781239eae881f2844",
                displayName: "Jonathan Castroviejo",
                normName: "jonathan-castroviejo",
                nationality: "Spain",
                team: "team-sky",
                pageUrl: "https://www.procyclingstats.com/rider/jonathan-castroviejo",
                age: "31",
                height: "1.71",
                weight: "62",
                grandTours: 9,
                classicRaces: 7,
                proWins: 9,
                sportRadarId: "sr:rider:39819",
            },
            {
                _id: "5bee8eb781239eae881f26ef",
                displayName: "Kristijan Koren",
                normName: "kristijan-koren",
                nationality: "Slovenia",
                team: "bahrain-merida-pro-cycling-team",
                pageUrl: "https://www.procyclingstats.com/rider/kristijan-koren",
                age: "31",
                height: "1.83",
                weight: "72",
                grandTours: 9,
                classicRaces: 21,
                proWins: 3,
                sportRadarId: "sr:rider:39822",
            },
            {
                _id: "5bee8eb781239eae881f272c",
                displayName: "Peter Sagan",
                normName: "peter-sagan",
                nationality: "Slovakia",
                team: "bora-hansgrohe",
                pageUrl: "https://www.procyclingstats.com/rider/peter-sagan",
                age: "28",
                height: "1.84",
                weight: "73",
                grandTours: 11,
                classicRaces: 25,
                proWins: 109,
                sportRadarId: "sr:rider:39823",
            },
            {
                _id: "5bee8eb781239eae881f2868",
                displayName: "Michael Matthews",
                normName: "michael-matthews",
                nationality: "Australia",
                team: "team-sunweb",
                pageUrl: "https://www.procyclingstats.com/rider/michael-matthews",
                age: "28",
                height: "1.8",
                weight: null,
                grandTours: 8,
                classicRaces: 12,
                proWins: 33,
                sportRadarId: "sr:rider:39828",
            },
            {
                _id: "5bee8eb781239eae881f289e",
                displayName: "Alexander Kristoff",
                normName: "alexander-kristoff",
                nationality: "Norway",
                team: "uae-team-emirates",
                pageUrl: "https://www.procyclingstats.com/rider/alexander-kristoff",
                age: "31",
                height: "1.81",
                weight: "78",
                grandTours: 8,
                classicRaces: 23,
                proWins: 71,
                sportRadarId: "sr:rider:41433",
            },
            {
                _id: "5bee8eb781239eae881f2820",
                displayName: "Steven Kruijswijk",
                normName: "steven-kruijswijk",
                nationality: "Netherlands",
                team: "team-lottonl-jumbo",
                pageUrl: "https://www.procyclingstats.com/rider/steven-kruijswijk",
                age: "31",
                height: "1.78",
                weight: "66",
                grandTours: 15,
                classicRaces: 6,
                proWins: 2,
                sportRadarId: "sr:rider:41446",
            },
            {
                _id: "5bee8eb781239eae881f27e7",
                displayName: "Sep Vanmarcke",
                normName: "sep-vanmarcke",
                nationality: "Belgium",
                team: "team-ef-education-first-drapac-p-b-cannondale",
                pageUrl: "https://www.procyclingstats.com/rider/sep-vanmarcke",
                age: "30",
                height: "1.9",
                weight: "77",
                grandTours: 6,
                classicRaces: 19,
                proWins: 6,
                sportRadarId: "sr:rider:41449",
            },
            {
                _id: "5bee8eb781239eae881f2763",
                displayName: "Jens Keukeleire",
                normName: "jens-keukeleire",
                nationality: "Belgium",
                team: "lotto-soudal",
                pageUrl: "https://www.procyclingstats.com/rider/jens-keukeleire",
                age: "29",
                height: "1.85",
                weight: "69",
                grandTours: 7,
                classicRaces: 26,
                proWins: 11,
                sportRadarId: "sr:rider:41623",
            },
            {
                _id: "5bee8eb781239eae881f26b7",
                displayName: "Tony Gallopin",
                normName: "tony-gallopin",
                nationality: "France",
                team: "ag2r-la-mondiale",
                pageUrl: "https://www.procyclingstats.com/rider/tony-gallopin",
                age: "30",
                height: "1.8",
                weight: "70",
                grandTours: 10,
                classicRaces: 24,
                proWins: 12,
                sportRadarId: "sr:rider:44301",
            },
            {
                _id: "5bee8eb781239eae881f276d",
                displayName: "Jack Bauer",
                normName: "jack-bauer",
                nationality: "New",
                team: "mitchelton-scott",
                pageUrl: "https://www.procyclingstats.com/rider/jack-bauer",
                age: "33",
                height: "1.91",
                weight: "74",
                grandTours: 6,
                classicRaces: 16,
                proWins: 6,
                sportRadarId: "sr:rider:45187",
            },
            {
                _id: "5bee8eb781239eae881f276b",
                displayName: "Luke Durbridge",
                normName: "luke-durbridge",
                nationality: "Australia",
                team: "mitchelton-scott",
                pageUrl: "https://www.procyclingstats.com/rider/luke-durbridge",
                age: "27",
                height: "1.87",
                weight: "78",
                grandTours: 8,
                classicRaces: 15,
                proWins: 11,
                sportRadarId: "sr:rider:47984",
            },
            {
                _id: "5bee8eb781239eae881f27db",
                displayName: "Julien Vermote",
                normName: "julien-vermote",
                nationality: "Belgium",
                team: "team-dimension-data",
                pageUrl: "https://www.procyclingstats.com/rider/julien-vermote",
                age: "29",
                height: "1.79",
                weight: "71",
                grandTours: 7,
                classicRaces: 13,
                proWins: 3,
                sportRadarId: "sr:rider:47987",
            },
            {
                _id: "5bee8eb781239eae881f26e1",
                displayName: "Ion Izagirre",
                normName: "ion-izagirre",
                nationality: "Spain",
                team: "bahrain-merida-pro-cycling-team",
                pageUrl: "https://www.procyclingstats.com/rider/ion-izagirre",
                age: "29",
                height: "1.73",
                weight: "60",
                grandTours: 8,
                classicRaces: 18,
                proWins: 9,
                sportRadarId: "sr:rider:47988",
            },
            {
                _id: "5bee8eb781239eae881f2778",
                displayName: "Michael Hepburn",
                normName: "michael-hepburn",
                nationality: "Australia",
                team: "mitchelton-scott",
                pageUrl: "https://www.procyclingstats.com/rider/michael-hepburn",
                age: "27",
                height: "1.86",
                weight: "77",
                grandTours: 5,
                classicRaces: 4,
                proWins: 3,
                sportRadarId: "sr:rider:47989",
            },
            {
                _id: "5bee8eb781239eae881f27ee",
                displayName: "Taylor Phinney",
                normName: "taylor-phinney",
                nationality: "United",
                team: "team-ef-education-first-drapac-p-b-cannondale",
                pageUrl: "https://www.procyclingstats.com/rider/taylor-phinney",
                age: "28",
                height: "1.97",
                weight: "82",
                grandTours: 5,
                classicRaces: 12,
                proWins: 13,
                sportRadarId: "sr:rider:49558",
            },
            {
                _id: "5bee8eb781239eae881f2a3c",
                displayName: "Romain Hardy",
                normName: "romain-hardy",
                nationality: "France",
                team: "fortuneo-samsic",
                pageUrl: "https://www.procyclingstats.com/rider/romain-hardy",
                age: "30",
                height: "1.72",
                weight: "62",
                grandTours: 5,
                classicRaces: 3,
                proWins: 2,
                sportRadarId: "sr:rider:49561",
            },
            {
                _id: "5bee8eb781239eae881f2a2f",
                displayName: "Laurent Pichon",
                normName: "laurent-pichon",
                nationality: "France",
                team: "fortuneo-samsic",
                pageUrl: "https://www.procyclingstats.com/rider/laurent-pichon",
                age: "32",
                height: "1.78",
                weight: "69",
                grandTours: 6,
                classicRaces: 7,
                proWins: 3,
                sportRadarId: "sr:rider:49567",
            },
            {
                _id: "5bee8eb781239eae881f2a33",
                displayName: "Florian Vachon",
                normName: "florian-vachon",
                nationality: "France",
                team: "fortuneo-samsic",
                pageUrl: "https://www.procyclingstats.com/rider/florian-vachon",
                age: "33",
                height: "1.79",
                weight: "65",
                grandTours: 5,
                classicRaces: 5,
                proWins: 6,
                sportRadarId: "sr:rider:49569",
            },
            {
                _id: "5bee8eb781239eae881f2709",
                displayName: "Damiano Caruso",
                normName: "damiano-caruso",
                nationality: "Italy",
                team: "bmc-racing-team",
                pageUrl: "https://www.procyclingstats.com/rider/damiano-caruso",
                age: "31",
                height: "1.79",
                weight: "67",
                grandTours: 10,
                classicRaces: 19,
                proWins: 1,
                sportRadarId: "sr:rider:49690",
            },
            {
                _id: "5bee8eb781239eae881f2a9d",
                displayName: "Andrea Pasqualon",
                normName: "andrea-pasqualon",
                nationality: "Italy",
                team: "wanty-groupe-gobert",
                pageUrl: "https://www.procyclingstats.com/rider/andrea-pasqualon",
                age: "30",
                height: "1.74",
                weight: "68",
                grandTours: 2,
                classicRaces: 7,
                proWins: 7,
                sportRadarId: "sr:rider:49955",
            },
            {
                _id: "5bee8eb781239eae881f27c0",
                displayName: "Tom-Jelte Slagter",
                normName: "tom-jelte-slagter",
                nationality: "Netherlands",
                team: "team-dimension-data",
                pageUrl: "https://www.procyclingstats.com/rider/tom-jelte-slagter",
                age: "29",
                height: "1.69",
                weight: "58",
                grandTours: 8,
                classicRaces: 16,
                proWins: 8,
                sportRadarId: "sr:rider:50027",
            },
            {
                _id: "5bee8eb781239eae881f2892",
                displayName: "Darwin Atapuma",
                normName: "darwin-atapuma",
                nationality: "Colombia",
                team: "uae-team-emirates",
                pageUrl: "https://www.procyclingstats.com/rider/darwin-atapuma",
                age: "30",
                height: "1.67",
                weight: "59",
                grandTours: 10,
                classicRaces: 6,
                proWins: 4,
                sportRadarId: "sr:rider:50029",
            },
            {
                _id: "5bee8eb781239eae881f2935",
                displayName: "Nicolas Edet",
                normName: "nicolas-edet",
                nationality: "France",
                team: "cofidis-solutions-credits",
                pageUrl: "https://www.procyclingstats.com/rider/nicolas-edet",
                age: "30",
                height: "1.76",
                weight: "60",
                grandTours: 8,
                classicRaces: 6,
                proWins: 2,
                sportRadarId: "sr:rider:50032",
            },
            {
                _id: "5bee8eb781239eae881f279e",
                displayName: "Nairo Quintana",
                normName: "nairo-quintana",
                nationality: "Colombia",
                team: "movistar-team",
                pageUrl: "https://www.procyclingstats.com/rider/nairo-quintana",
                age: "28",
                height: "1.67",
                weight: "59",
                grandTours: 12,
                classicRaces: 5,
                proWins: 36,
                sportRadarId: "sr:rider:50044",
            },
            {
                _id: "5bee8eb781239eae881f27fb",
                displayName: "Marcel Kittel",
                normName: "marcel-kittel",
                nationality: "Germany",
                team: "team-katusha-alpecin",
                pageUrl: "https://www.procyclingstats.com/rider/marcel-kittel",
                age: "30",
                height: "1.88",
                weight: "82",
                grandTours: 9,
                classicRaces: 3,
                proWins: 88,
                sportRadarId: "sr:rider:50212",
            },
            {
                _id: "5bee8eb781239eae881f2874",
                displayName: "John Degenkolb",
                normName: "john-degenkolb",
                nationality: "Germany",
                team: "trek-segafredo",
                pageUrl: "https://www.procyclingstats.com/rider/john-degenkolb",
                age: "29",
                height: "1.8",
                weight: "77",
                grandTours: 12,
                classicRaces: 19,
                proWins: 46,
                sportRadarId: "sr:rider:50219",
            },
            {
                _id: "5bee8eb781239eae881f2859",
                displayName: "Tom Dumoulin",
                normName: "tom-dumoulin",
                nationality: "Netherlands",
                team: "team-sunweb",
                pageUrl: "https://www.procyclingstats.com/rider/tom-dumoulin",
                age: "28",
                height: "1.85",
                weight: "69",
                grandTours: 10,
                classicRaces: 16,
                proWins: 21,
                sportRadarId: "sr:rider:50279",
            },
            {
                _id: "5bee8eb781239eae881f26f6",
                displayName: "Sonny Colbrelli",
                normName: "sonny-colbrelli",
                nationality: "Italy",
                team: "bahrain-merida-pro-cycling-team",
                pageUrl: "https://www.procyclingstats.com/rider/sonny-colbrelli",
                age: "28",
                height: "1.76",
                weight: "71",
                grandTours: 7,
                classicRaces: 11,
                proWins: 22,
                sportRadarId: "sr:rider:50283",
            },
            {
                _id: "5bee8eb781239eae881f2851",
                displayName: "Luke Rowe",
                normName: "luke-rowe",
                nationality: "Great",
                team: "team-sky",
                pageUrl: "https://www.procyclingstats.com/rider/luke-rowe",
                age: "28",
                height: "1.85",
                weight: "72",
                grandTours: 6,
                classicRaces: 17,
                proWins: 2,
                sportRadarId: "sr:rider:50285",
            },
            {
                _id: "5bee8eb781239eae881f2841",
                displayName: "Michał Kwiatkowski",
                normName: "michal-kwiatkowski",
                nationality: "Poland",
                team: "team-sky",
                pageUrl: "https://www.procyclingstats.com/rider/michal-kwiatkowski",
                age: "28",
                height: "1.76",
                weight: "68",
                grandTours: 8,
                classicRaces: 22,
                proWins: 27,
                sportRadarId: "sr:rider:50288",
            },
            {
                _id: "5bee8eb781239eae881f2a92",
                displayName: "Guillaume Van Keirsbulck",
                normName: "guillaume-van-keirsbulck",
                nationality: "Belgium",
                team: "wanty-groupe-gobert",
                pageUrl: "https://www.procyclingstats.com/rider/guillaume-van-keirsbulck",
                age: "27",
                height: "1.92",
                weight: "85",
                grandTours: 3,
                classicRaces: 12,
                proWins: 6,
                sportRadarId: "sr:rider:50429",
            },
            {
                _id: "5bee8eb781239eae881f2722",
                displayName: "Rafał Majka",
                normName: "rafal-majka",
                nationality: "Poland",
                team: "bora-hansgrohe",
                pageUrl: "https://www.procyclingstats.com/rider/rafal-majka",
                age: "29",
                height: "1.73",
                weight: "62",
                grandTours: 14,
                classicRaces: 12,
                proWins: 11,
                sportRadarId: "sr:rider:50708",
            },
            {
                _id: "5bee8eb781239eae881f2a99",
                displayName: "Thomas Degand",
                normName: "thomas-degand",
                nationality: "Belgium",
                team: "wanty-groupe-gobert",
                pageUrl: "https://www.procyclingstats.com/rider/thomas-degand",
                age: "32",
                height: "1.76",
                weight: "63",
                grandTours: 3,
                classicRaces: 5,
                proWins: 1,
                sportRadarId: "sr:rider:50709",
            },
            {
                _id: "5bee8eb781239eae881f291b",
                displayName: "Jesús Herrada",
                normName: "jesus-herrada-lopez",
                nationality: "Spain",
                team: "cofidis-solutions-credits",
                pageUrl: "https://www.procyclingstats.com/rider/jesus-herrada-lopez",
                age: "28",
                height: "1.83",
                weight: "72",
                grandTours: 6,
                classicRaces: 15,
                proWins: 9,
                sportRadarId: "sr:rider:50710",
            },
            {
                _id: "5bee8eb781239eae881f2955",
                displayName: "Jérôme Cousin",
                normName: "jerome-cousin",
                nationality: "France",
                team: "direct-energie",
                pageUrl: "https://www.procyclingstats.com/rider/jerome-cousin",
                age: "29",
                height: "1.8",
                weight: "74",
                grandTours: 6,
                classicRaces: 9,
                proWins: 2,
                sportRadarId: "sr:rider:50906",
            },
            {
                _id: "5bee8eb781239eae881f26bd",
                displayName: "Dmitriy Gruzdev",
                normName: "dmitriy-gruzdev",
                nationality: "Kazakhstan",
                team: "astana-pro-team",
                pageUrl: "https://www.procyclingstats.com/rider/dmitriy-gruzdev",
                age: "32",
                height: "1.83",
                weight: "72",
                grandTours: 6,
                classicRaces: 13,
                proWins: 8,
                sportRadarId: "sr:rider:57419",
            },
            {
                _id: "5bee8eb781239eae881f273a",
                displayName: "Arnaud Démare",
                normName: "arnaud-demare",
                nationality: "France",
                team: "groupama-fdj",
                pageUrl: "https://www.procyclingstats.com/rider/arnaud-demare",
                age: "27",
                height: "1.82",
                weight: "78",
                grandTours: 6,
                classicRaces: 17,
                proWins: 56,
                sportRadarId: "sr:rider:66818",
            },
            {
                _id: "5bee8eb781239eae881f2737",
                displayName: "Ramon Sinkeldam",
                normName: "ramon-sinkeldam",
                nationality: "Netherlands",
                team: "groupama-fdj",
                pageUrl: "https://www.procyclingstats.com/rider/ramon-sinkeldam",
                age: "29",
                height: "1.93",
                weight: "77",
                grandTours: 6,
                classicRaces: 14,
                proWins: 7,
                sportRadarId: "sr:rider:66828",
            },
            {
                _id: "5bee8eb781239eae881f26b3",
                displayName: "Romain Bardet",
                normName: "romain-bardet",
                nationality: "France",
                team: "ag2r-la-mondiale",
                pageUrl: "https://www.procyclingstats.com/rider/romain-bardet",
                age: "28",
                height: "1.84",
                weight: "65",
                grandTours: 7,
                classicRaces: 12,
                proWins: 7,
                sportRadarId: "sr:rider:67014",
            },
            {
                _id: "5bee8eb781239eae881f2744",
                displayName: "Tobias Ludvigsson",
                normName: "tobias-ludvigsson",
                nationality: "Sweden",
                team: "groupama-fdj",
                pageUrl: "https://www.procyclingstats.com/rider/tobias-ludvigsson",
                age: "27",
                height: "1.94",
                weight: "76",
                grandTours: 9,
                classicRaces: 4,
                proWins: 4,
                sportRadarId: "sr:rider:68828",
            },
            {
                _id: "5bee8eb781239eae881f27b1",
                displayName: "Tim Declercq",
                normName: "tim-declercq",
                nationality: "Belgium",
                team: "quick-step-floors",
                pageUrl: "https://www.procyclingstats.com/rider/tim-declercq",
                age: "29",
                height: "1.9",
                weight: "78",
                grandTours: 2,
                classicRaces: 11,
                proWins: 0,
                sportRadarId: "sr:rider:77857",
            },
            {
                _id: "5bee8eb781239eae881f273c",
                displayName: "Rudy Molard",
                normName: "rudy-molard",
                nationality: "France",
                team: "groupama-fdj",
                pageUrl: "https://www.procyclingstats.com/rider/rudy-molard",
                age: "29",
                height: "1.78",
                weight: "62",
                grandTours: 8,
                classicRaces: 7,
                proWins: 2,
                sportRadarId: "sr:rider:78671",
            },
            {
                _id: "5bee8eb781239eae881f27c8",
                displayName: "Reinardt Janse van Rensburg",
                normName: "reinardt-janse-van-rensburg",
                nationality: "South",
                team: "team-dimension-data",
                pageUrl: "https://www.procyclingstats.com/rider/reinardt-janse-van-rensburg",
                age: "29",
                height: "1.82",
                weight: "74",
                grandTours: 5,
                classicRaces: 12,
                proWins: 9,
                sportRadarId: "sr:rider:81383",
            },
            {
                _id: "5bee8eb781239eae881f276e",
                displayName: "Damien Howson",
                normName: "damien-howson",
                nationality: "Australia",
                team: "mitchelton-scott",
                pageUrl: "https://www.procyclingstats.com/rider/damien-howson",
                age: "26",
                height: "1.88",
                weight: "68",
                grandTours: 6,
                classicRaces: 4,
                proWins: 2,
                sportRadarId: "sr:rider:88950",
            },
            {
                _id: "5bee8eb781239eae881f27bd",
                displayName: "Bob Jungels",
                normName: "bob-jungels",
                nationality: "Luxembourg",
                team: "quick-step-floors",
                pageUrl: "https://www.procyclingstats.com/rider/bob-jungels",
                age: "26",
                height: "1.89",
                weight: "72",
                grandTours: 6,
                classicRaces: 7,
                proWins: 17,
                sportRadarId: "sr:rider:88956",
            },
            {
                _id: "5bee8eb781239eae881f27fa",
                displayName: "Ian Boswell",
                normName: "ian-boswell",
                nationality: "United",
                team: "team-katusha-alpecin",
                pageUrl: "https://www.procyclingstats.com/rider/ian-boswell",
                age: "27",
                height: "1.85",
                weight: "70",
                grandTours: 5,
                classicRaces: 3,
                proWins: 0,
                sportRadarId: "sr:rider:91752",
            },
            {
                _id: "5bee8eb781239eae881f2a36",
                displayName: "Warren Barguil",
                normName: "warren-barguil",
                nationality: "France",
                team: "fortuneo-samsic",
                pageUrl: "https://www.procyclingstats.com/rider/warren-barguil",
                age: "27",
                height: "1.83",
                weight: "60",
                grandTours: 8,
                classicRaces: 11,
                proWins: 4,
                sportRadarId: "sr:rider:91766",
            },
            {
                _id: "5bee8eb781239eae881f26b0",
                displayName: "Alexis Vuillermoz",
                normName: "alexis-vuillermoz",
                nationality: "France",
                team: "ag2r-la-mondiale",
                pageUrl: "https://www.procyclingstats.com/rider/alexis-vuillermoz",
                age: "30",
                height: "1.74",
                weight: "60",
                grandTours: 6,
                classicRaces: 7,
                proWins: 7,
                sportRadarId: "sr:rider:91768",
            },
            {
                _id: "5bee8eb781239eae881f27a4",
                displayName: "Yves Lampaert",
                normName: "yves-lampaert",
                nationality: "Belgium",
                team: "quick-step-floors",
                pageUrl: "https://www.procyclingstats.com/rider/yves-lampaert",
                age: "27",
                height: "1.8",
                weight: "75",
                grandTours: 3,
                classicRaces: 8,
                proWins: 8,
                sportRadarId: "sr:rider:93161",
            },
            {
                _id: "5bee8eb781239eae881f2862",
                displayName: "Nikias Arndt",
                normName: "nikias-arndt",
                nationality: "Germany",
                team: "team-sunweb",
                pageUrl: "https://www.procyclingstats.com/rider/nikias-arndt",
                age: "26",
                height: "1.88",
                weight: "77.5",
                grandTours: 7,
                classicRaces: 13,
                proWins: 5,
                sportRadarId: "sr:rider:93179",
            },
            {
                _id: "5bee8eb781239eae881f26cf",
                displayName: "Omar Fraile",
                normName: "omar-fraile",
                nationality: "Spain",
                team: "astana-pro-team",
                pageUrl: "https://www.procyclingstats.com/rider/omar-fraile",
                age: "28",
                height: "1.84",
                weight: "69",
                grandTours: 7,
                classicRaces: 5,
                proWins: 6,
                sportRadarId: "sr:rider:93811",
            },
        ],
        _id: "5bfac5af7b541d4ebc5b195f",
        isActive: true,
        hasResults: false,
        teamsRiders: [],
        riderResults: [],
        bets: [],
        __v: 0,
    }